server:
  port: 8989
spring:
  datasource:
    username: root
    password: hsp
    url: jdbc:mysql://localhost:3306/boot_shop?useSSL=false&amp;useUnicode=true&amp;characterEncoding=UTF-8
    druid:
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: hsp
        reset-enable: false
      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
          config:
            delete-allow: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
  type-aliases-package: com.kfhstu.beans  #类型别名bean
#  mapper-locations: #指定mapper地址，使用mapperScan注解替代，也可用默认地址（/mapper/**/*.xml）